// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOiqLOiH4FXo6ZhNUuVBanlJe1FR3b4I',
    appId: '1:876132552901:web:38e596d60b7c242680e0ac',
    messagingSenderId: '876132552901',
    projectId: 'chore-app-flutter',
    authDomain: 'chore-app-flutter.firebaseapp.com',
    storageBucket: 'chore-app-flutter.appspot.com',
    measurementId: 'G-50BE2G1516',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMAnRfdAmyxmAoRF9B0ANx0UmCIlvbcsk',
    appId: '1:876132552901:android:405d39092514aebc80e0ac',
    messagingSenderId: '876132552901',
    projectId: 'chore-app-flutter',
    storageBucket: 'chore-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXwfc1ciO-00-tVkVbEkiFlk7XEFkYIIY',
    appId: '1:876132552901:ios:d009cbcaed2fe55980e0ac',
    messagingSenderId: '876132552901',
    projectId: 'chore-app-flutter',
    storageBucket: 'chore-app-flutter.appspot.com',
    iosBundleId: 'com.example.fluttertodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXwfc1ciO-00-tVkVbEkiFlk7XEFkYIIY',
    appId: '1:876132552901:ios:d009cbcaed2fe55980e0ac',
    messagingSenderId: '876132552901',
    projectId: 'chore-app-flutter',
    storageBucket: 'chore-app-flutter.appspot.com',
    iosBundleId: 'com.example.fluttertodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlOiqLOiH4FXo6ZhNUuVBanlJe1FR3b4I',
    appId: '1:876132552901:web:b80009b94bca822480e0ac',
    messagingSenderId: '876132552901',
    projectId: 'chore-app-flutter',
    authDomain: 'chore-app-flutter.firebaseapp.com',
    storageBucket: 'chore-app-flutter.appspot.com',
    measurementId: 'G-K1ZEBXBYQQ',
  );
}
